logging:
  config: classpath:logback.xml
  path: d:/appHome/log
server:
  port: 8083
  session-timeout: 60


mybatis:
     mapperLocations: classpath:/mapper/*.xml
     mapperScanPackage: com.xxyp.admin.server.dao
     configLocation: classpath:/springConfig/mybatis-config.xml

mysql:
    datasource:
        readSize: 2  #读库个数
        type: com.alibaba.druid.pool.DruidDataSource
        mapperLocations: classpath:/mapper/*.xml
        configLocation: classpath:/springConfig/mybatis-config.xml
        write:
           url: jdbc:mysql://10.0.10.134:3346/sinafq?useUnicode=true&characterEncoding=utf-8
           username: sinafenqi
           password: hU3OZhLyCI
           driver-class-name: com.mysql.jdbc.Driver
           minIdle: 5
           maxActive: 100
           initialSize: 10
           maxWait: 60000
           timeBetweenEvictionRunsMillis: 60000
           minEvictableIdleTimeMillis: 300000
           validationQuery: select 'x'
           testWhileIdle: true
           testOnBorrow: false
           testOnReturn: false
           poolPreparedStatements: true
           maxPoolPreparedStatementPerConnectionSize: 50
           removeAbandoned: true
           filters: stat
        read01:
           url: jdbc:mysql://10.0.10.134:3346/sinafq?useUnicode=true&characterEncoding=utf-8
           username: sinafenqi
           password: hU3OZhLyCI
           driver-class-name: com.mysql.jdbc.Driver
           minIdle: 5
           maxActive: 100
           initialSize: 10
           maxWait: 60000
           timeBetweenEvictionRunsMillis: 60000
           minEvictableIdleTimeMillis: 300000
           validationQuery: select 'x'
           testWhileIdle: true
           testOnBorrow: false
           testOnReturn: false
           poolPreparedStatements: true
           maxPoolPreparedStatementPerConnectionSize: 50
           removeAbandoned: true
           filters: stat
        read02:
           url: jdbc:mysql://10.0.10.134:3346/sinafq?useUnicode=true&characterEncoding=utf-8
           username: sinafenqi
           password: hU3OZhLyCI
           driver-class-name: com.mysql.jdbc.Driver
           minIdle: 5
           maxActive: 100
           initialSize: 10
           maxWait: 60000
           timeBetweenEvictionRunsMillis: 60000
           minEvictableIdleTimeMillis: 300000
           validationQuery: select 'x'
           testWhileIdle: true
           testOnBorrow: false
           testOnReturn: false
           poolPreparedStatements: true
           maxPoolPreparedStatementPerConnectionSize: 50
           removeAbandoned: true
           filters: stat  
           
           
spring:
  application:
      name: admin-service

eureka:
  server:
    port: 8761
  instance:
    hostname: 127.0.0.1
    lease-expiration-duration-in-seconds: 30
    ease-renewal-interval-in-seconds: 50
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.server.port}/eureka/
      
ribbon:
  eureka:
    enabled: true

           